<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="keywords" content="Watauga,Robotics,FTC,VEX,Sumo,ASU">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<title></title>
		<link href="/media/images/wataugarobotics.png" rel="icon" type="image/png">

		<!-- CSS (picnic, custom) -->
		<link href="/media/css/picnic.min.css" rel="stylesheet" type="text/css"/>
		<link href="/media/css/custom.css" rel="stylesheet" type="text/css"/>

		<!-- JS (fontawesome) -->
		<script src="https://use.fontawesome.com/bb5602ef6a.js"></script>
	</head>
	<body>
		<!-- Navigation -->
		<nav class="main">
			<a href="/" class="brand">
				<img class="logo" src="/media/images/wataugarobotics.png" alt=""/>
				<span>Watauga Robotics</span>
			</a>

			<!-- responsive-->
			<input id="bmenu" type="checkbox" class="show">
			<label for="bmenu" class="burger pseudo button">&#8801;</label>

			<div class="menu">
				<a href="/ftc/index.html" class="pseudo button">FTC</a>
				<a href="/vex/index.html" class="pseudo button">VEX</a>
				<a href="/sumo/index.html" class="pseudo button">Sumo</a>
				<a href="https://github.com/wataugarobotics" class="pseudo button"><i class="fa fa-github" style="color:white"></i> GitHub</a>
			</div>
		</nav>
		<main class="content">
									extends: sumo.j2
default_block: content

		</main>
		<footer>
			<center><a href="https://github.com/wataugarobotics/wataugarobotics"><h6>
					&#169; 2017 Watauga Robotics [MIT License]
			</h6></a></center>
		</footer>
	</body>
</html>